### ISSUE TITLE
No module named requests

### ISSUE THREAD

**Issue by AriaMoradi** [Frojd/django-react-templatetags#44]
Somehow importing `django_react_templatetags.context_processors.react_context_processor` in `settings.TEMPLATES` throws a error that `requests` in not installed and the problem goes away if I install the `requests` library

here is what i got
```
(venv) D:\Desktop\django-es-modules-template-tags>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "D:\Desktop\django-es-modules-template-tags\venv\lib\site-packages\django\template\utils.py", line 66, in __getitem__
    return self._engines[alias]
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Desktop\django-es-modules-template-tags\venv\lib\site-packages\django\template\backends\django.py", line 121, in get_package_libraries
    module = import_module(entry[1])
  File "C:\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Desktop\django-es-modules-template-tags\venv\lib\site-packages\django_react_templatetags\templatetags\react.py", line 14, in <module>
    from django_react_templatetags.ssr import SSRService
  File "D:\Desktop\django-es-modules-template-tags\venv\lib\site-packages\django_react_templatetags\ssr.py", line 10, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Desktop\django-es-modules-template-tags\venv\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "D:\Desktop\django-es-modules-template-tags\venv\lib\site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "D:\Desktop\django-es-modules-template-tags\venv\lib\site-packages\django\core\management\base.py", line 395, in check
    include_deployment_checks=include_deployment_checks,
  File "D:\Desktop\django-es-modules-template-tags\venv\lib\site-packages\django\core\management\base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "D:\Desktop\django-es-modules-template-tags\venv\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "D:\Desktop\django-es-modules-template-tags\venv\lib\site-packages\django\contrib\admin\checks.py", line 76, in check_dependencies
    for engine in engines.all():
  File "D:\Desktop\django-es-modules-template-tags\venv\lib\site-packages\django\template\utils.py", line 90, in all
    return [self[alias] for alias in self]
  File "D:\Desktop\django-es-modules-template-tags\venv\lib\site-packages\django\template\utils.py", line 90, in <listcomp>
    return [self[alias] for alias in self]
  File "D:\Desktop\django-es-modules-template-tags\venv\lib\site-packages\django\template\utils.py", line 81, in __getitem__
    engine = engine_cls(params)
  File "D:\Desktop\django-es-modules-template-tags\venv\lib\site-packages\django\template\backends\django.py", line 25, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "D:\Desktop\django-es-modules-template-tags\venv\lib\site-packages\django\template\backends\django.py", line 43, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "D:\Desktop\django-es-modules-template-tags\venv\lib\site-packages\django\template\backends\django.py", line 108, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "D:\Desktop\django-es-modules-template-tags\venv\lib\site-packages\django\template\backends\django.py", line 125, in get_package_libraries
    "trying to load '%s': %s" % (entry[1], e)
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'django_react_templatetags.templatetags.react': No module named 'reque
sts'
```

**Comment by AriaMoradi** [comment]
looks like `requests` is being imported inside `django_template_tags.ssr`:

```ssr.py

import logging

from django.conf import settings
import requests
import json


logger = logging.getLogger(__name__)

# rest of the file...
```

**Comment by AriaMoradi** [comment]
according to the documentation of setuptools, `extras_require` is used for:
```
A dictionary mapping names of “extras” (optional features of your project) to strings or lists of strings specifying what other distributions must be installed to support those features. See the section below on Declaring Dependencies for details and examples of the format of this argument.
```
So i think `import requests` should be a conditional import.
